# Generated by Django 5.2.4 on 2025-07-18 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel", "0002_hotel_address_hotel_check_in_hotel_check_out_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fixed",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "relative",
                    models.DecimalField(decimal_places=3, max_digits=6, null=True),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fixed__isnull", False),
                            ("relative__isnull", False),
                            _connector="XOR",
                        ),
                        name="fixed_or_relative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SeasonSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotel_finances.price",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_sales",
                        related_query_name="season_sale",
                        to="hotel.hotel",
                    ),
                ),
            ],
        ),
    ]
