# Generated by Django 5.2.4 on 2025-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="fixed",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="relative",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=None, max_digits=6, null=True
            ),
        ),
    ]
