# Generated by Django 5.2.4 on 2025-07-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_finances", "0002_alter_price_fixed_alter_price_relative"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonsale",
            name="date_from",
            field=models.DateField(default="2010-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonsale",
            name="date_to",
            field=models.DateField(default="2010-10-10"),
            preserve_default=False,
        ),
    ]
