# Generated by Django 5.2.4 on 2025-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_clients", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientStatus",
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("SD", "Standard"), ("VP", "VIP")], default="SD", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
