# Generated by Django 5.2.4 on 2025-07-18 22:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel", "0002_hotel_address_hotel_check_in_hotel_check_out_and_more"),
        ("hotel_clients", "0001_initial"),
        ("hotel_finances", "0001_initial"),
        ("hotel_infrastructure", "0001_initial"),
        ("hotel_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_length", models.IntegerField(null=True)),
                (
                    "discount",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotel_finances.price",
                    ),
                ),
                (
                    "included_options",
                    models.ManyToManyField(
                        related_name="packages",
                        related_query_name="package",
                        to="hotel_service.additionaloption",
                    ),
                ),
                (
                    "included_services",
                    models.ManyToManyField(
                        related_name="packages",
                        related_query_name="package",
                        to="hotel_service.service",
                    ),
                ),
                (
                    "mealplan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        related_query_name="package",
                        to="hotel_service.mealplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guests_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("date_in", models.DateField()),
                ("planned_date_out", models.DateField()),
                ("factual_date_out", models.DateField(null=True)),
                ("early_check_in", models.BooleanField(default=False)),
                ("late_check_out", models.BooleanField(default=False)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("QR", "QR"),
                            ("PS", "POS"),
                            ("CS", "Cash"),
                            ("PP", "Pre-Paid"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RR", "Reserved"),
                            ("CC", "Cancelled"),
                            ("NS", "No Show"),
                            ("PY", "Payed"),
                            ("CI", "Checked In"),
                            ("CO", "Checked Out"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        related_query_name="reservation",
                        to="hotel_clients.client",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        related_query_name="reservation",
                        to="hotel.hotel",
                    ),
                ),
                (
                    "mealplan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        related_query_name="reservation",
                        to="hotel_service.mealplan",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="reservations",
                        related_query_name="reservation",
                        to="hotel_service.service",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        related_query_name="reservation",
                        to="hotel_reservations.reservationpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guests_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "additional_options",
                    models.ManyToManyField(
                        related_name="reservations",
                        related_query_name="reservation",
                        to="hotel_service.additionaloption",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserved_rooms",
                        related_query_name="reserved_room",
                        to="hotel_reservations.reservation",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        related_query_name="reservation",
                        to="hotel_infrastructure.room",
                    ),
                ),
            ],
        ),
    ]
