# Generated by Django 5.2.4 on 2025-07-19 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_alter_hotel_address_alter_hotel_email_and_more"),
        ("hotel_clients", "0002_delete_clientstatus_client_status_alter_client_email"),
        ("hotel_reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="client",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                related_query_name="reservation",
                to="hotel_clients.client",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="hotel",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                related_query_name="reservation",
                to="hotel.hotel",
            ),
            preserve_default=False,
        ),
    ]
