# Generated by Django 5.2.4 on 2025-07-18 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel_infrastructure", "0001_initial"),
        ("hotel_staff", "0005_designation_salary_staff_salary_coef"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("lock_id", models.CharField(max_length=100)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locks",
                        related_query_name="locks",
                        to="hotel_infrastructure.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LockGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock_groups",
                        related_query_name="lock_group",
                        to="hotel_infrastructure.building",
                    ),
                ),
                (
                    "locks",
                    models.ManyToManyField(
                        related_name="groups",
                        related_query_name="group",
                        to="hotel_security.lock",
                    ),
                ),
                (
                    "permitted_departments",
                    models.ManyToManyField(
                        related_name="permitted_lock_groups",
                        related_query_name="permitted_lock_group",
                        to="hotel_staff.department",
                    ),
                ),
                (
                    "permitted_designations",
                    models.ManyToManyField(
                        related_name="permitted_lock_groups",
                        related_query_name="permitted_lock_group",
                        to="hotel_staff.designation",
                    ),
                ),
                (
                    "permitted_staff",
                    models.ManyToManyField(
                        related_name="permitted_lock_groups",
                        related_query_name="permitted_lock_group",
                        to="hotel_staff.staff",
                    ),
                ),
            ],
        ),
    ]
