# Generated by Django 5.2.4 on 2025-07-18 22:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel", "0002_hotel_address_hotel_check_in_hotel_check_out_and_more"),
        ("hotel_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=500, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="RoomFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_living", models.BooleanField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        related_query_name="building",
                        to="hotel.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        related_query_name="floor",
                        to="hotel_infrastructure.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("area", models.FloatField(null=True)),
                (
                    "beds",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "additional_beds",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("description", models.TextField(max_length=1000, null=True)),
                ("notes", models.TextField(blank=True, max_length=1000)),
                ("specific_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "available_options",
                    models.ManyToManyField(
                        related_name="available_in_rooms",
                        related_query_name="available_in_room",
                        to="hotel_service.additionaloption",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        related_query_name="room",
                        to="hotel_infrastructure.floor",
                    ),
                ),
                (
                    "included_mealplan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="included_in_rooms",
                        related_query_name="included_in_room",
                        to="hotel_service.mealplan",
                    ),
                ),
                (
                    "included_options",
                    models.ManyToManyField(
                        related_name="included_in_rooms",
                        related_query_name="included_in_room",
                        to="hotel_service.additionaloption",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        related_query_name="room",
                        to="hotel_infrastructure.roomcategory",
                    ),
                ),
                (
                    "feature",
                    models.ManyToManyField(
                        related_name="rooms",
                        related_query_name="room",
                        to="hotel_infrastructure.roomfeature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomCleaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleanings",
                        related_query_name="cleaning",
                        to="hotel_infrastructure.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=400)),
                ("image_description", models.CharField(max_length=150)),
                ("image", models.ImageField(upload_to="")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        related_query_name="image",
                        to="hotel_infrastructure.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomUnavailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("BK", "Booking"),
                            ("CL", "Cleaning"),
                            ("MT", "Maintenance"),
                        ],
                        max_length=2,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_till", models.DateField(null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        related_query_name="state",
                        to="hotel_infrastructure.room",
                    ),
                ),
            ],
        ),
    ]
