# Generated by Django 5.2.4 on 2025-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_booking",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roomcategory",
            name="description",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roomfeature",
            name="description",
            field=models.TextField(blank=True, default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roomunavailability",
            name="reason",
            field=models.CharField(
                choices=[("CL", "Cleaning"), ("MT", "Maintenance")], max_length=2
            ),
        ),
        migrations.DeleteModel(
            name="RoomCleaning",
        ),
    ]
