# Generated by Django 5.2.4 on 2025-07-19 14:58

import django.core.validators
import hotel_infrastructure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_infrastructure", "0002_room_is_booking_alter_room_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="address",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="name",
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(99)]
            ),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="image",
            field=models.ImageField(
                upload_to=hotel_infrastructure.models.RoomImage._get_image_path
            ),
        ),
    ]
