# Generated by Django 5.2.4 on 2025-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaloption",
            name="description",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="additionaloption",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="description",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
