# Generated by Django 5.2.4 on 2025-07-18 22:08
import datetime

import hotel.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="address",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="check_in",
            field=models.TimeField(default=datetime.time(hour=14, minute=0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel",
            name="check_out",
            field=models.TimeField(default=datetime.time(hour=11, minute=0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel",
            name="check_window",
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                default=None, upload_to=hotel.models.Hotel._get_image_path, null=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel",
            name="phone_numer",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
