# Generated by Django 5.2.4 on 2025-07-19 14:37

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_hotel_address_hotel_check_in_hotel_check_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="address",
            field=models.CharField(blank=True, default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hotel",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hotel",
            name="phone_numer",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="", max_length=128, region=None
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hotel",
            name="website",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
