# Generated by Django 5.2.4 on 2025-07-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_alter_hotel_address_alter_hotel_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="phone_numer",
            new_name="phone_number",
        ),
    ]
