# Generated by Django 5.2.4 on 2025-07-17 13:03

import django.db.models.deletion
import functools
import hotel.validators
import hotel_staff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designations",
                        related_query_name="designation",
                        to="hotel_staff.department",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designation",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="staff",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        validators=[
                            functools.partial(
                                hotel.validators.is_digit,
                                *(),
                                **{
                                    "message": "В номере телефона допускаются лишь цифры"
                                },
                            ),
                            functools.partial(
                                hotel.validators.specific_length,
                                *(),
                                **{
                                    "length": 10,
                                    "message": "Длина номера телефона должна быть 10 цифр, вышло {got}",
                                },
                            ),
                        ]
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                (
                    "image",
                    models.ImageField(upload_to=hotel_staff.models.Staff._image_path),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="hotel_staff.designation",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="hotel.hotel",
                    ),
                ),
            ],
        ),
    ]
