# Generated by Django 5.2.4 on 2025-07-17 13:28

import hotel_staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_staff", "0002_remove_designation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="image",
            field=models.ImageField(
                null=True, upload_to=hotel_staff.models.Staff._image_path
            ),
        ),
    ]
