# Generated by Django 5.2.4 on 2025-07-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_staff", "0003_alter_staff_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeadOfDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heads",
                        related_query_name="head",
                        to="hotel_staff.department",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hod",
                        to="hotel_staff.staff",
                    ),
                ),
            ],
        ),
    ]
