# Generated by Django 5.2.4 on 2025-07-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_staff", "0004_headofdepartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="designation",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="salary_coef",
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
            preserve_default=False,
        ),
    ]
