# Generated by Django 5.2.4 on 2025-07-18 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_hotel_address_hotel_check_in_hotel_check_out_and_more"),
        ("hotel_staff", "0005_designation_salary_staff_salary_coef"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designation",
            name="salary",
        ),
        migrations.CreateModel(
            name="DesignationSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_staff.designation",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
                    ),
                ),
            ],
        ),
    ]
