# Generated by Django 5.2.4 on 2025-07-18 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_staff", "0006_remove_designation_salary_designationsalary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designationsalary",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salaries",
                related_query_name="salary",
                to="hotel_staff.designation",
            ),
        ),
    ]
