# Generated by Django 5.2.4 on 2025-07-19 13:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_staff", "0007_alter_designationsalary_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
