# Generated by Django 5.2.4 on 2025-07-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_staff", "0008_alter_staff_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "permissions": [
                    ("edit_mission_critical", "Manage employee's role and salary")
                ]
            },
        ),
    ]
